import operator
from typing import Annotated, Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field


# How many articles to send per LLM batch call
BATCH_SIZE = 10


class ArticleData(BaseModel):
    """A single news article fetched from Benzinga."""
    title: str
    body: str  # HTML-stripped plain text
    tickers: List[str] = Field(default_factory=list)
    published: Optional[str] = None
    url: Optional[str] = None
    benzinga_id: Optional[int] = None
    finbert_sentiment: Optional[float] = Field(None, description="Pre-computed FinBERT sentiment score (-1 to +1)")


class ArticleScore(BaseModel):
    """Scores assigned to a single article by the Analyst."""
    benzinga_id: Optional[int] = None
    title: str = ""
    tickers: List[str] = Field(default_factory=list)
    sentiment_score: float = Field(..., ge=-1.0, le=1.0, description="Sentiment from -1.0 (very negative) to +1.0 (very positive)")
    price_direction_score: int = Field(..., ge=1, le=10, description="Price direction from 1 (strong sell) to 10 (strong buy)")
    reasoning: str = ""
    finbert_sentiment: Optional[float] = Field(None, description="Raw FinBERT sentiment score (-1 to +1)")


class TickerAggregate(BaseModel):
    """Aggregated scores for a single ticker across all its articles."""
    ticker: str
    num_articles: int
    avg_sentiment: float
    avg_price_direction: float
    avg_finbert_sentiment: Optional[float] = Field(None, description="Average raw FinBERT sentiment across articles")
    article_scores: List[ArticleScore] = Field(default_factory=list)
    overall_reasoning: str = ""


class SentimentState(BaseModel):
    """Global state for the sentiment analysis pipeline."""
    date_str: str = Field(..., description="Date string for Benzinga query (e.g. '2025-06-01')")
    ticker_filter: Optional[str] = Field(None, description="Optional ticker to filter articles")
    logs_dir: Optional[str] = Field(None, description="Path to directory for logging artifacts")

    # Phase 0: LLM-optimized prompt (generated by prompt_optimizer node)
    optimized_analyst_prompt: Optional[str] = Field(None, description="LLM-generated optimized system prompt for the analyst")

    # Phase 1: Collection
    collected_articles: List[ArticleData] = Field(default_factory=list)

    # Phase 2: Per-article analysis (uses operator.add reducer for parallel fan-in)
    article_scores: Annotated[List[Dict[str, Any]], operator.add] = Field(default_factory=list)

    # Phase 3: Aggregation
    ticker_aggregates: List[TickerAggregate] = Field(default_factory=list)

    # Usage tracking (same pattern as lab_01)
    llm_calls: Annotated[List[Dict[str, Any]], operator.add] = Field(default_factory=list)
    node_usage: Dict[str, Dict[str, Any]] = Field(default_factory=dict)
    total_usage: Dict[str, Any] = Field(
        default_factory=lambda: {"input_tokens": 0, "output_tokens": 0, "total_tokens": 0, "total_cost": 0.0}
    )
